openapi: 3.0.0
info:
  title: Charger API
  description: API to manage charger devices
  version: "1.0"
servers:
  - url: https://0trws66xs2.execute-api.us-east-2.amazonaws.com/prod/
paths:
  /chargers:
    get:
      summary: List all chargers
      operationId: getAllChargers
      tags:
        - Chargers
      responses:
        '200':
          description: A list of chargers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Charger'
    post:
      summary: Create a new charger
      operationId: createCharger
      tags:
        - Chargers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Charger'
      responses:
        '201':
          description: Charger created
  /chargers/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Get a charger by ID
      operationId: getCharger
      tags:
        - Chargers
      responses:
        '200':
          description: Details of a charger
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Charger'
    put:
      summary: Update a charger
      operationId: updateCharger
      tags:
        - Chargers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Charger'
      responses:
        '200':
          description: Charger updated
    delete:
      summary: Delete a charger
      operationId: deleteCharger
      tags:
        - Chargers
      responses:
        '204':
          description: Charger deleted
components:
  schemas:
    Charger:
      type: object
      required:
        - id
        - name
        - status
        - location
        - networkProtocol
        - publicVisibility
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        status:
          type: string
          enum:
            - active
            - disabled
            - out of order
        location:
          type: object
          properties:
            latitude:
              type: number
              format: float
            longitude:
              type: number
              format: float
        networkProtocol:
          type: string
        publicVisibility:
          type: boolean
